### ISSUE TITLE
Add a CI Tool ex: CircleCI, TravisCI

### ISSUE THREAD

**Issue by Ashish0077** [NJACKWinterOfCode/RoboTalk#14]
**What is CI?**
Continuous integration (CI) is the practice of automating the integration of code changes from multiple contributors into a single software project.

**Comment by Ashish0077** [comment]
I would like to work on Integrating Circle CI on this project

**Comment by somenath1435** [comment]
@Ashish0077 yes you can integrate

**Comment by s-ayush2903** [comment]
@somenath1435 can you please add some label(indicating **level_of_difficulty)in** this issue?
 And I'm fixing it as well

**Comment by ShivangiSingh17** [comment]
@Ashish0077 are you still working on this issue?
