### ISSUE TITLE
New Features Required

### ISSUE THREAD

**Issue by parjanyaacoder** [NJACKWinterOfCode/RoboTalk#18]
The text converted from speech can not be copied.If multiline text is added in the text to be converted in Speech it is presented in only 1 line. 
![Screenshot_20191203-181351_RoboTalk](https://user-images.githubusercontent.com/46294122/70053029-92f8af00-15fa-11ea-80ec-5aac8d3eaf6b.jpg)
![Screenshot_20191203-181616_RoboTalk](https://user-images.githubusercontent.com/46294122/70053051-9be98080-15fa-11ea-807d-f10068586f22.jpg)
![Screenshot_20191203-181832_RoboTalk](https://user-images.githubusercontent.com/46294122/70053069-a6a41580-15fa-11ea-8a02-85a28cdfa95b.jpg)
![Screenshot_20191203-170918_RoboTalk](https://user-images.githubusercontent.com/46294122/70053115-bfacc680-15fa-11ea-80f3-d44914c57927.jpg)

I want to work on this issue.Can I?

**Comment by somenath1435** [comment]
@parjanyaacoder go ahead

**Comment by parjanyaacoder** [comment]
Please accept my previous pr

**Comment by somenath1435** [comment]
@parjanyaacoder no need to ping on gitter everytime, When I'm free, I'll review
