### ISSUE TITLE
Add Skip button

### ISSUE THREAD

**Issue by somenath1435** [NJACKWinterOfCode/RoboTalk#23]
The app should have a skip login button, we should not force anyone to register.

**Comment by MahmoudMabrok** [comment]
Is It still available?

**Comment by Sarthak2601** [comment]
@MahmoudMabrok It got done in the PR #24 buddy.

**Comment by MahmoudMabrok** [comment]
please close it to not confuse any one.

**Comment by SubhradeepSS** [comment]
Issue fixed in PR#25

**Comment by Sarthak2601** [comment]
@SubhradeepSS it was already fixed in PR #24
