### ISSUE TITLE
Change app logo 

### ISSUE THREAD

**Issue by Mehulipal** [NJACKWinterOfCode/RoboTalk#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mehulipal** [comment]
I am working on it

**Comment by ShivangiSingh17** [comment]
@Mehulipal you need to explain the issue. You can edit the one above. Can you please do it.

**Comment by Mehulipal** [comment]
# Is your feature request related to a problem? Please describe
The existing app logo does not seem to be in sync with the app name.
# Describe the solution you'd like
I would like to change the logo.
# Describe alternatives you've considered
Alternatively, the existing logo can be dropped.
# Additional context
![image](https://user-images.githubusercontent.com/54908756/71788870-7c57d480-304c-11ea-825a-88093978b719.png)
